"""Demo 工具：安全、确定性、fake-only 的本地工具。

中文学习边界：
这些工具注册在 production TOOL_REGISTRY 中，通过完整的 Tool pipeline
（TOOL_GATE → TOOL_INVOKE → TOOL_RESULT）执行。它们不读 .env、不调外部 API、
不读私人资料、不执行 shell、不访问网络。

demo.echo_task_summary (confirmation="never", zero-arg):
  - 返回确定性的任务摘要，零副作用
  - risk_level=low, 无需用户确认

demo.write_demo_note (confirmation="always"):
  - 写入文件到受控 demo workspace 路径
  - risk_level=medium, 需用户确认
  - 参数全可选（兼容 turn-end hook 的 tool_input={}），默认写入 workspace/demo/

为什么存在：
- 为 First Usable Task MVP 提供安全、可审计的 demo 工具
- 验证 Tool pipeline 可承载非空业务操作（不仅是 noop gate 测试）
- 用户可见：模型在 demo/fake 场景中可看到这些工具，turn-end hook 可触发完整管线
"""

from __future__ import annotations

import tempfile
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# demo.echo_task_summary
# ---------------------------------------------------------------------------
from agent.tool_registry import register_tool


@register_tool(
    name="demo.echo_task_summary",
    description=(
        "【demo 工具】返回当前 demo 任务的确定性摘要。"
        "适用场景：用户要求「总结任务」「查看任务摘要」「汇总当前进度」等。"
        "何时不该调用：用户只是闲聊或问不相关的问题时不应调用。"
        "安全说明：零副作用、零网络调用、不读私人资料、无需用户确认。"
    ),
    parameters={},
    confirmation="never",
    capability="local_action",
    risk_level="low",
    output_policy="bounded_text",
    meta_tool=False,
)
def demo_echo_task_summary() -> str:
    """返回确定性的任务摘要，演示 Tool pipeline 的非空业务操作路径。"""
    return (
        "[demo.echo_task_summary] "
        "任务摘要：这是一个 First Agent 本地 demo 任务。"
        "provider=fake，无外部 API 调用，无网络访问，无私人数据读取。"
        "本工具通过完整的 TOOL_GATE → TOOL_INVOKE → TOOL_RESULT 管线执行。"
    )


# ---------------------------------------------------------------------------
# demo.write_demo_note
# ---------------------------------------------------------------------------


DEMO_WORKSPACE_SUBDIR = ("workspace", "demo")
_FORBIDDEN_DEMO_PATH_NAMES = {".env", "agent_log.jsonl"}
_FORBIDDEN_DEMO_PATH_PARTS = {"sessions", "runs", "memory", "skills"}


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent


def _default_demo_note_path() -> Path:
    """默认 demo note 路径：workspace/demo/<UTC timestamp>/note.md"""
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return _project_root() / Path(*DEMO_WORKSPACE_SUBDIR) / stamp / "note.md"


def _validate_demo_note_path(target: Path) -> Path:
    """验证 demo note 路径安全：必须在 workspace/demo/ 或 tmp 目录内。"""
    resolved = target.expanduser().resolve()
    raw_parts = set(resolved.parts)
    if resolved.name in _FORBIDDEN_DEMO_PATH_NAMES:
        raise ValueError(f"demo path is reserved: {resolved}")
    if raw_parts & _FORBIDDEN_DEMO_PATH_PARTS:
        raise ValueError(f"demo path overlaps runtime artifact directory: {resolved}")

    project_demo_root = (_project_root() / Path(*DEMO_WORKSPACE_SUBDIR)).resolve()
    tmp_root = Path(tempfile.gettempdir()).resolve()

    def _is_within(parent: Path, child: Path) -> bool:
        try:
            child.relative_to(parent)
            return True
        except ValueError:
            return False

    if _is_within(project_demo_root, resolved) or _is_within(tmp_root, resolved):
        return resolved
    raise ValueError(
        f"demo write rejected: path escapes allowed workspace. "
        f"Allowed: {project_demo_root} or {tmp_root}"
    )


@register_tool(
    name="demo.write_demo_note",
    description=(
        "【demo 工具】写入一个 demo note 到受控的 workspace/demo/ 目录。"
        "适用场景：用户要求「创建笔记」「写 demo note」「记录验证结果」等写入操作。"
        "何时不该调用：用户只是查看/阅读/查询时不应调用，用文字直接回答即可。"
        "安全说明：不写用户真实目录、不读私人资料、不访问网络。需用户确认后才执行。"
        "参数：path 和 content 均为可选——不传时使用安全的默认路径和内容。"
    ),
    parameters={
        "path": {
            "type": "string",
            "description": "目标文件路径（必须在 workspace/demo/ 或 tmp 内）",
        },
        "content": {
            "type": "string",
            "description": "要写入的文本内容",
        },
    },
    confirmation="always",
    capability="file_write",
    risk_level="medium",
    output_policy="bounded_text",
    meta_tool=False,
)
def demo_write_demo_note(path: str = "", content: str = "") -> str:
    """在受控 demo workspace 内写入 note 文件。

    所有参数均可选（兼容 turn-end hook 的 tool_input={}）。
    不传参数时使用安全默认值，写入 workspace/demo/<timestamp>/note.md。
    """
    target = _default_demo_note_path() if not path else Path(path)

    if not content:
        content = (
            f"# Demo Note\n"
            f"created: {datetime.now(timezone.utc).isoformat()}\n"
            f"provider: fake\n"
            f"note: generated by demo.write_demo_note with no API key, no network.\n"
        )

    try:
        safe = _validate_demo_note_path(target)
    except ValueError as exc:
        return f"[demo.write_demo_note] blocked: {exc}"

    safe.parent.mkdir(parents=True, exist_ok=True)
    safe.write_text(content, encoding="utf-8")
    byte_count = safe.stat().st_size
    return (
        f"[demo.write_demo_note] ok: wrote {byte_count} bytes to {safe}. "
        f"no API key, no network."
    )
