"""Skill System 内部实现包。

本包负责 skill 的安装、加载、解析、注册与安全检查。当前为内部实现，
无稳定顶层 public API；外部应直接导入具体子模块：
    from agent.skills.registry import ...
    from agent.skills.loader import ...
    from agent.skills.installer import ...
"""