"""Local agent productization demo (fake provider, no network, no secrets).

中文学习边界：
- 这是 Local Agent Productization RFC 的最小服务/用例层。
- CLI 只做 argv 解析；本模块负责编排 fake provider → 工具动作 → ToolResult →
  TraceEvent → 最终答复。
- 不导入 ``agent.core`` / ``agent.tool_executor`` / ``agent.checkpoint``，
  不实例化真实 Anthropic client，不读 ``.env`` / ``agent_log.jsonl`` /
  ``sessions/`` / ``runs/`` / 真实 MCP config。
- 文件写入只允许在显式 demo workspace 内（``workspace/demo/`` 或
  ``tempfile.gettempdir()`` 子目录），任何越界路径都通过
  ``UnsafeDemoPathError`` 直接拒绝。
- ToolResult 通过 ``agent.tool_result_contract.classify_tool_result``
  统一归一化；TraceEvent 通过 ``agent.runtime_trace_projection`` 构造，
  与 RFC 0001 / RFC 0002 的 trace 形状完全一致。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
import tempfile
import uuid
from typing import Any

from agent.local_trace import TraceEvent, redact_trace_metadata
from agent.runtime_trace_projection import build_tool_result_trace_event
from agent.tool_result_contract import ToolResultEnvelope, classify_tool_result


PROVIDER_NAME = "fake"
DEMO_WORKSPACE_SUBDIR = ("workspace", "demo")
_FORBIDDEN_PATH_NAMES = {".env", "agent_log.jsonl"}
_FORBIDDEN_PATH_PARTS = {"sessions", "runs", "memory", "skills"}
_DEFAULT_TASK = "create a demo note about today's local agent run"


class UnsafeDemoPathError(ValueError):
    """demo 工作区路径越界（落在敏感目录或项目外）时抛出。"""


@dataclass(frozen=True, slots=True)
class PlannedAction:
    """fake provider 输出的下一步动作；纯数据，无副作用。"""

    tool_name: str
    tool_input: dict[str, Any]
    description: str


@dataclass(frozen=True, slots=True)
class DemoStep:
    """单步 demo 执行结果，含 ToolResult envelope 与 TraceEvent。"""

    action: PlannedAction
    tool_result_text: str
    envelope: ToolResultEnvelope
    trace_event: TraceEvent


@dataclass(frozen=True, slots=True)
class DemoResult:
    """整个 demo 闭环的可观察输出。"""

    task: str
    provider: str
    workspace: Path
    steps: tuple[DemoStep, ...]
    final_answer: str
    trace_events: tuple[TraceEvent, ...] = field(default_factory=tuple)


class FakeProvider:
    """Deterministic local provider.

    中文学习边界：fake provider 只把任务字符串映射到一份固定计划，**不**做
    模型调用、不读 secret、不联网。任何未来真实 provider 必须走单独 opt-in
    RFC，不应在这里偷偷加分支。
    """

    name = PROVIDER_NAME

    def plan(self, task: str, workspace: Path) -> list[PlannedAction]:
        normalized_task = (task or _DEFAULT_TASK).strip() or _DEFAULT_TASK
        note_path = workspace / "note.md"
        content = (
            "# Local Agent Demo Note\n"
            f"task: {normalized_task}\n"
            "provider: fake\n"
            "note: generated by agent.local_demo with no API key, no network.\n"
        )
        return [
            PlannedAction(
                tool_name="demo.write_demo_note",
                tool_input={"path": str(note_path), "content": content},
                description=f"write a demo note describing the task to {note_path.name}",
            )
        ]


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _is_within(parent: Path, child: Path) -> bool:
    try:
        child.relative_to(parent)
        return True
    except ValueError:
        return False


def _validate_demo_workspace(path: Path) -> Path:
    """限制 demo workspace 只能落在 ``workspace/demo/`` 或 tmp 目录内。

    中文学习边界：demo 不应该读写真实 runtime artifact，也不应该写到
    项目外随机路径。这里参考 ``agent/local_trace.py`` 的策略：先按文件名
    / 路径段拒绝敏感目录，再用 ``resolve()`` 检查是否落在允许根下。
    """

    raw_parts = set(path.parts)
    if path.name in _FORBIDDEN_PATH_NAMES:
        raise UnsafeDemoPathError(f"demo workspace path is reserved: {path}")
    if raw_parts & _FORBIDDEN_PATH_PARTS:
        raise UnsafeDemoPathError(
            f"demo workspace path overlaps a runtime artifact directory: {path}"
        )

    resolved = path.expanduser().resolve()
    project_demo_root = (_project_root() / Path(*DEMO_WORKSPACE_SUBDIR)).resolve()
    tmp_root = Path(tempfile.gettempdir()).resolve()
    if _is_within(project_demo_root, resolved) or _is_within(tmp_root, resolved):
        return resolved
    raise UnsafeDemoPathError(
        "demo workspace must live under workspace/demo/ or tempfile.gettempdir()"
    )


def resolve_demo_workspace(override: str | Path | None = None) -> Path:
    """返回受控的 demo workspace 路径，必要时自动创建子目录。

    默认在 ``workspace/demo/<UTC timestamp>/`` 下生成新目录，避免覆盖历史
    artifact；调用方可以传 ``override``（仍然走 ``_validate_demo_workspace``）。
    """

    if override is not None:
        candidate = Path(override)
    else:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        candidate = _project_root() / Path(*DEMO_WORKSPACE_SUBDIR) / stamp

    safe = _validate_demo_workspace(candidate)
    safe.mkdir(parents=True, exist_ok=True)
    return safe


def _execute_action(action: PlannedAction, workspace: Path) -> str:
    """在受控 workspace 内执行单个 PlannedAction，返回 legacy 风格 tool result。

    中文学习边界：这里**不**调用 ``agent.tool_executor``。tool_executor 与
    runtime brain 紧耦合，引入会污染 demo 边界。本切片只支持一种安全动作
    （``demo.write_demo_note``），调用方在写入前再次校验路径在 workspace 内。
    """

    if action.tool_name != "demo.write_demo_note":
        return f"Error: unsupported demo action: {action.tool_name}"

    target = Path(action.tool_input.get("path", ""))
    content = action.tool_input.get("content", "")
    try:
        target_resolved = target.expanduser().resolve()
    except OSError as exc:
        return f"Error: invalid demo path: {exc}"
    if not _is_within(workspace, target_resolved):
        return f"Error: demo write rejected (path escapes workspace): {target}"

    target_resolved.parent.mkdir(parents=True, exist_ok=True)
    target_resolved.write_text(content, encoding="utf-8")
    byte_count = target_resolved.stat().st_size
    return (
        f"Wrote demo note to {target_resolved} ({byte_count} bytes). "
        "no API key, no network."
    )


def run_local_demo(
    task: str | None = None,
    *,
    workspace: str | Path | None = None,
    provider: FakeProvider | None = None,
) -> DemoResult:
    """编排一次完整的 fake demo 循环并返回 ``DemoResult``。"""

    active_provider = provider or FakeProvider()
    safe_workspace = (
        _validate_demo_workspace(Path(workspace))
        if workspace is not None
        else resolve_demo_workspace()
    )
    safe_workspace.mkdir(parents=True, exist_ok=True)

    normalized_task = (task or _DEFAULT_TASK).strip() or _DEFAULT_TASK
    run_id = f"demo-{uuid.uuid4().hex[:12]}"
    trace_id = f"trace-{uuid.uuid4().hex[:12]}"

    actions = active_provider.plan(normalized_task, safe_workspace)
    steps: list[DemoStep] = []
    trace_events: list[TraceEvent] = []
    for index, action in enumerate(actions, start=1):
        result_text = _execute_action(action, safe_workspace)
        envelope = classify_tool_result(result_text)
        trace_event = build_tool_result_trace_event(
            run_id=run_id,
            trace_id=trace_id,
            span_id=f"span-{index}",
            parent_span_id=None,
            tool_name=action.tool_name,
            tool_result=result_text,
            step_id=f"step-{index}",
        )
        steps.append(
            DemoStep(
                action=action,
                tool_result_text=result_text,
                envelope=envelope,
                trace_event=trace_event,
            )
        )
        trace_events.append(trace_event)

    if steps and steps[-1].envelope.status == "executed":
        last_path = steps[-1].action.tool_input.get("path", "<unknown>")
        final_answer = f"wrote demo note to {last_path}"
    else:
        final_answer = "demo did not complete successfully; see step output above."

    completion_event = TraceEvent(
        run_id=run_id,
        trace_id=trace_id,
        span_id=f"span-{len(steps) + 1}",
        parent_span_id=None,
        span_type="state_transition",
        name="demo.complete",
        status="ok" if steps and steps[-1].envelope.status == "executed" else "failed",
        step_id="step-complete",
        metadata={"task": normalized_task, "provider": active_provider.name},
    )
    trace_events.append(completion_event)

    return DemoResult(
        task=normalized_task,
        provider=active_provider.name,
        workspace=safe_workspace,
        steps=tuple(steps),
        final_answer=final_answer,
        trace_events=tuple(trace_events),
    )


def format_demo_result(result: DemoResult) -> str:
    """把 ``DemoResult`` 渲染成单屏可读输出（presenter 边界）。"""

    safe_task = redact_trace_metadata({"task": result.task})["task"]
    lines: list[str] = []
    lines.append(
        f"[Local Agent Demo] provider={result.provider} workspace={result.workspace}"
    )
    lines.append(f"Task : {safe_task}")
    for index, step in enumerate(result.steps, start=1):
        # ``executed`` 是 ToolResult envelope 的内部归一化状态；面向用户输出统一
        # 用更友好的 ``ok``，失败状态保持原样以便排查。
        status_label = "ok" if step.envelope.status == "executed" else step.envelope.status
        lines.append(
            f"Step {index} {step.action.tool_name} -> {status_label}"
        )
        path = step.action.tool_input.get("path")
        if path:
            lines.append(f"  path  : {path}")
        lines.append(f"  bytes : {step.envelope.content_length}")
        if step.envelope.status != "executed":
            lines.append(f"  error : {step.envelope.error_type or 'unknown'}")
    lines.append(f"Final: {result.final_answer}")
    lines.append(f"Trace summary ({len(result.trace_events)} events):")
    for event in result.trace_events:
        redacted = redact_trace_metadata(event.metadata)
        suffix = ""
        if "task" in redacted:
            suffix = f" task={redacted['task']!r}"
        lines.append(
            f"  {event.span_id} {event.span_type} {event.name} {event.status}{suffix}"
        )
    lines.append(f"Inspect: open {result.workspace} for the generated artifact.")
    return "\n".join(lines) + "\n"


def run_demo_cli(argv: list[str]) -> int:
    """``main.py demo`` 子命令的入口（CLI thin adapter）。

    只接受可选位置参数 ``task`` 与可选 ``--workspace PATH``；其余语义全部走
    ``run_local_demo`` / ``format_demo_result``。
    """

    task: str | None = None
    workspace_override: str | None = None
    rest = list(argv)
    while rest:
        arg = rest.pop(0)
        if arg == "--workspace":
            if not rest:
                print("Error: --workspace requires a path argument.")
                return 2
            workspace_override = rest.pop(0)
        elif arg in {"-h", "--help"}:
            print(
                "Usage: python main.py demo [TASK] [--workspace PATH]\n"
                "Runs a fake-provider local demo; no API key, no network."
            )
            return 0
        elif task is None:
            task = arg
        else:
            print(f"Error: unexpected argument: {arg}")
            return 2

    try:
        result = run_local_demo(task, workspace=workspace_override)
    except UnsafeDemoPathError as exc:
        print(f"Error: {exc}")
        return 2
    print(format_demo_result(result), end="")
    return 0
